from django.urls import path
from .views import *
urlpatterns = [
	path("",login_view,name='login'),
	path("home/",home,name='home'),
    path('a_panel',admin_panel,name='admin_panel'),
    path('logout',logout_view,name='logout'),
    path('add_user/',add_user,name='add_user'),
    path('add-tashkilot/', add_tashkilot, name='add_tashkilot'),
    path('add-avto/', add_avto, name='add_avto'),
    path('add-yoqilgi/', add_yoqilgi, name='add_yoqilgi'),
    path('statistics/', statistics_view, name='statistics'),
    path('api/statistics/data/', get_statistics_data, name='statistics_data'),
    path('api/statistics/filters/', get_filter_options, name='statistics_filters'),
    path('yoqilgi-quyish/', yoqilgi_quyish, name='yoqilgi_quyish'),
    path('bugungi-yoqilgilar/', bugungi_yoqilgilar, name='bugungi_yoqilgilar'),
    path('add-fuel/', add_fuel, name='add_fuel'),
    path('send-telegram/', send_telegram, name='send_telegram'),
    path('api/today-fuel/', get_today_fuel_api, name='today_fuel'),
    path('api/avtomobillar/', get_avtomobillar_api, name='avtomobillar'),
    path('export-statistics-excel/', export_statistics_excel, name='export_statistics_excel'),
    path('export-today-excel/', export_today_excel, name='export_today_excel'),
    path('tashkilot/edit/<int:pk>/', tashkilot_edit, name='tashkilot_edit'),
    path('tashkilot/delete/<int:pk>/', tashkilot_delete, name='tashkilot_delete'),
    path('avto/edit/<int:pk>/', avto_edit, name='avto_edit'),
    path('avto/delete/<int:pk>/', avto_delete, name='avto_delete'),
    path('yoqilgi-turi/edit/<int:pk>/', yoqilgi_turi_edit, name='yoqilgi_turi_edit'),
    path('yoqilgi-turi/delete/<int:pk>/', yoqilgi_turi_delete, name='yoqilgi_turi_delete'),
]