# Generated by Django 5.2.7 on 2025-10-20 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('avto_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Yoqilgi_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compilated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hajm', models.IntegerField(default=0)),
                ('created_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.avto')),
                ('who_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tashkilot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tashkilot')),
            ],
        ),
    ]
