# Generated by Django 5.2.7 on 2025-10-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_avto_tashkilot_yoqilgi_turi_compilated'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='tashkilot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tashkilot'),
        ),
    ]
