# Generated by Django 5.2.7 on 2025-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_avto_tashkilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashkilot',
            name='group_id',
            field=models.IntegerField(default=4885110792),
        ),
    ]
