# Generated by Django 5.2.7 on 2025-10-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tashkilot_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilated',
            name='photo',
            field=models.FileField(default='none.jpg', upload_to='static/images/'),
        ),
    ]
