# Generated by Django 5.2.7 on 2025-10-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_compilated_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoqilgi_turi',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
