# Generated by Django 5.2.7 on 2025-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_yoqilgi_turi_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilated',
            name='all_price',
            field=models.IntegerField(default=0),
        ),
    ]
