# Generated by Django 5.2.7 on 2025-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_compilated_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilated',
            name='hajm',
            field=models.FloatField(default=0),
        ),
    ]
