# Generated by Django 5.2.7 on 2025-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_compilated_hajm'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilated',
            name='yoqilgi_turi',
            field=models.CharField(default='AI-82', max_length=50),
        ),
        migrations.AlterField(
            model_name='compilated',
            name='all_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='yoqilgi_turi',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
