# Generated by Django 5.2.7 on 2025-11-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_compilated_yoqilgi_turi_alter_compilated_all_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='tashkilot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tashkilot'),
        ),
    ]
