# Generated by Django 5.2.7 on 2025-11-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_avto_tashkilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilated',
            name='photo',
            field=models.FileField(default='none.jpg', upload_to='images/'),
        ),
    ]
