# Generated by Django 5.2.7 on 2025-11-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_compilated_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilated',
            name='photo_2',
            field=models.FileField(default='none.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='compilated',
            name='yoqilgi_turi',
            field=models.CharField(default='tanlanmagan', max_length=50),
        ),
    ]
