# Generated by Django 5.2.7 on 2025-11-13 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_compilated_photo_2_alter_compilated_yoqilgi_turi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('miqdori', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='compilated',
            name='avto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.avto'),
        ),
        migrations.AlterField(
            model_name='compilated',
            name='tashkilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tashkilot'),
        ),
        migrations.AlterField(
            model_name='compilated',
            name='who_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OmborTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor_ozgarishi', models.IntegerField()),
                ('sababi', models.CharField(blank=True, max_length=255, null=True)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarixlar', to='main.ombor')),
            ],
        ),
    ]
