# Generated by Django 5.2.7 on 2025-11-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ombor_alter_compilated_avto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ombortarix',
            name='sababi',
        ),
        migrations.AddField(
            model_name='yoqilgi_turi',
            name='ombor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ombor'),
        ),
    ]
