# Generated by Django 5.2.7 on 2025-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_ombortarix_sababi_yoqilgi_turi_ombor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombor',
            name='miqdori',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ombortarix',
            name='miqdor_ozgarishi',
            field=models.FloatField(),
        ),
    ]
