# Generated by Django 5.2.7 on 2025-11-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_ombor_miqdori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilated',
            name='ombordan_ayirilgan',
            field=models.BooleanField(default=False),
        ),
    ]
