# Generated by Django 5.2.7 on 2025-11-15 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_compilated_ombordan_ayirilgan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TashkilotBalansTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qoldiq', models.DecimalField(decimal_places=2, max_digits=15)),
                ('izoh', models.CharField(max_length=255)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tashkilot Balans Tarixi',
                'verbose_name_plural': 'Tashkilot Balans Tarixlari',
                'ordering': ['-sana'],
            },
        ),
        migrations.AlterModelOptions(
            name='avto',
            options={'verbose_name': 'Avtomobil', 'verbose_name_plural': 'Avtomobillar'},
        ),
        migrations.AlterModelOptions(
            name='compilated',
            options={'ordering': ['-created_ad']},
        ),
        migrations.AlterModelOptions(
            name='tashkilot',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='yoqilgi_turi',
            options={'verbose_name': "Yoqilg'i turi", 'verbose_name_plural': "Yoqilg'i turlari"},
        ),
        migrations.AddField(
            model_name='compilated',
            name='tashkilotdan_ayirilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tashkilot',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='compilated',
            name='all_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tashkilot',
            name='group_id',
            field=models.BigIntegerField(default=4885110792),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='yoqilgi_turi',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='compilated',
            index=models.Index(fields=['created_ad'], name='main_compil_created_df82d6_idx'),
        ),
        migrations.AddIndex(
            model_name='compilated',
            index=models.Index(fields=['tashkilot', 'created_ad'], name='main_compil_tashkil_abee10_idx'),
        ),
        migrations.AddIndex(
            model_name='compilated',
            index=models.Index(fields=['avto', 'created_ad'], name='main_compil_avto_id_464bbc_idx'),
        ),
        migrations.AddField(
            model_name='tashkilotbalanstarix',
            name='tashkilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balans_tarix', to='main.tashkilot'),
        ),
    ]
