# Generated by Django 5.2.7 on 2025-11-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tashkilotbalanstarix_alter_avto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilated',
            name='qarz_holatida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tashkilot',
            name='max_qarz',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=15, verbose_name='Maksimal qarz miqdori'),
        ),
    ]
