# Generated by Django 5.2.7 on 2025-11-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_compilated_qarz_holatida_tashkilot_max_qarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=255)),
                ('message_id', models.IntegerField()),
                ('fuel_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_data', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='main_fuelme_status_6355a5_idx'), models.Index(fields=['callback_data'], name='main_fuelme_callbac_1129ca_idx')],
            },
        ),
    ]
