# Generated by Django 5.2.7 on 2025-11-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_fuelmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fuel Message', 'verbose_name_plural': 'Fuel Messages'},
        ),
        migrations.AlterField(
            model_name='fuelmessage',
            name='fuel_data',
            field=models.JSONField(default=dict),
        ),
    ]
